### ISSUE TITLE
Add API to set shutter open and close positions

### ISSUE THREAD

**Issue by GDYendell** [dls-controls/pmacFilterControl#35]
The pfc app only needs to know the close position. It should dynamically generate the command to send, which is currently a static:

```
char CLOSE_SHUTTER[] = "#5J=1000";
```

**Comment by GDYendell** [comment]
The pfc app only needs to know the close position. It does not open the shutter. The IOC can provide open/close by poking the motor record.

**Comment by OCopping** [comment]
Why does the command need to be dynamic? Based on a parameter the Beamline provide?

**Comment by GDYendell** [comment]
Yeah. It should correspond to the existing close position used for manual control in the IOC, whatever it happens to be set to.
